---
name: Feature Request
description: Request or propose a new feature
title: "[Feature Request]: <title>"
labels: ["New Feature"]
assignees:
  - insightsengineering/idr
body:
  - type: textarea
    attributes:
      label: Feature description
    validations:
      required: true
