---
name: Test Python package

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Run in all these versions of Python
        python-version: ["3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install pipenv
        run: pipx install pipenv

      - name: Install dependencies
        run: |
          pipenv run python --version
          pipenv install --deploy --dev

      - name: Run tests
        run: |
          pipenv run pytest --junit-xml=/tmp/junit.xml \
            --cache-clear --cov=presidio_cli tests/ | tee /tmp/coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /tmp/coverage.txt
          junitxml-path: /tmp/junit.xml

      - name: Check shell commands availibility
        run: |
          pipenv run python -m presidio_cli --help
          pipenv run presidio --help
